// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-14_Sf4obHxuVXr4HwyP5CTZUwOjcqfE',
    appId: '1:444941051938:web:7b98fb05bafa93c3fa427b',
    messagingSenderId: '444941051938',
    projectId: 'blood-donation-app-afa57',
    authDomain: 'blood-donation-app-afa57.firebaseapp.com',
    storageBucket: 'blood-donation-app-afa57.appspot.com',
    measurementId: 'G-SHWZ40NH69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAimeD8jvQIoCH4O-ubrya7mXyyRUkWKIY',
    appId: '1:444941051938:android:5b327c2324526f2bfa427b',
    messagingSenderId: '444941051938',
    projectId: 'blood-donation-app-afa57',
    storageBucket: 'blood-donation-app-afa57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVBoxjO1-fuoR9skj_AdjvtrIUmWWW1Nc',
    appId: '1:444941051938:ios:f1670bf30c81904ffa427b',
    messagingSenderId: '444941051938',
    projectId: 'blood-donation-app-afa57',
    storageBucket: 'blood-donation-app-afa57.appspot.com',
    iosBundleId: 'com.example.bloodDonationAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVBoxjO1-fuoR9skj_AdjvtrIUmWWW1Nc',
    appId: '1:444941051938:ios:f1670bf30c81904ffa427b',
    messagingSenderId: '444941051938',
    projectId: 'blood-donation-app-afa57',
    storageBucket: 'blood-donation-app-afa57.appspot.com',
    iosBundleId: 'com.example.bloodDonationAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-14_Sf4obHxuVXr4HwyP5CTZUwOjcqfE',
    appId: '1:444941051938:web:1ee2a91348010d47fa427b',
    messagingSenderId: '444941051938',
    projectId: 'blood-donation-app-afa57',
    authDomain: 'blood-donation-app-afa57.firebaseapp.com',
    storageBucket: 'blood-donation-app-afa57.appspot.com',
    measurementId: 'G-59XXMTSYZ3',
  );

}